### ISSUE TITLE
Add support for local files outside of vault

### ISSUE THREAD

**Issue by accelyte** [MSzturc/obsidian-better-pdf-plugin#10]
It's uncommon to store PDF documents as part of a knowledge management system. I personally would like to store PDF notes outside of the vault, and only reference them when I need to. I've tried the [syntaxes as mentioned on the forums](https://forum.obsidian.md/t/transclude-embed-external-files-present-on-the-computer/16389), but they don't seem to work. Is this possible?

**Comment by Gewerd-Strauss** [comment]
I second this, because I am currently sitting in front of the same problem. I don't exactly see why it wouldn't be possible, but that is more from a general standpoint, with no knowledge on the underlying language or structure of the plugin itself, I am certainly hopeful, because otherwhise this reduces in functionality drastically - unless I just declare half my hard drive a vault.

**Comment by kwetter** [comment]
is this plugin still maintained? If so I'd like to push this issue. Because I have a large folder structure full of pdfs outside the vault (which I sync over the cloud) I'd like to access them from within obsidian using this plugin. It allows me to include a small preview of a certain page. 
Unfortunately this is not possible for files outside the vault, although (at least) absolute referenced path are possible in obsidian. I wish for:
a) absolute paths even outside vault working in this plugin.
b) (since i often use different computers but synced folderstructures) also relative path references outside of the vault, or a way to adapt a full absolute path (by eg changing the network folder when changing clients)

**Comment by MSzturc** [comment]
I store most of my pdf's in the cloud too, in a separate folder that's not  part of my vault. I've created symlinks for them in my vault to access them in Obsidian.

I wont implement a feature where you can access files outside of obsidian, since it would cause security issues and break multi-platform compatibility of the obsidian vault.

**Comment by clavzno** [comment]
how do you create a symlink?
